#!/bin/bash

# requires: autoconf, libtool, libreadline-dev

mkdir ext
cd ext

#zookeeper
# wget https://archive.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz
# tar xzf zookeeper-3.4.6.tar.gz
# rm zookeeper-3.4.6.tar.gz
# mv zookeeper-3.4.6/src/c zookeeper
# rm -fr zookeeper-3.4.6
# cd zookeeper
# ./configure --prefix=$PWD
# make -j
# cd ..

# v2.6.1
# protobuf
# svn checkout http://protobuf.googlecode.com/svn/trunk/ protobuf
# cd protobuf
# ./autogen.sh
# ./configure --prefix=$PWD
# make -j
# cd ..

# googletest
# wget https://src.fedoraproject.org/lookaside/pkgs/gtest/gtest-1.6.0.zip/4577b49f2973c90bf9ba69aa8166b786/gtest-1.6.0.zip
# unzip gtest-1.6.0.zip
# rm gtest-1.6.0.zip
# mv gtest-1.6.0 googletest
# cd googletest
# ./configure --prefix=$PWD
# make -j
# cd ..


# zeromq
# wget http://download.zeromq.org/zeromq-2.1.11.tar.gz
# tar xzf zeromq-2.1.11.tar.gz
# rm zeromq-2.1.11.tar.gz
# mv zeromq-2.1.11 zeromq
# cd zeromq
# ./autogen.sh
# ./configure --prefix=$PWD
# make -j
# make install
# cd ..



